baseURL: "https://wallofshame.github.io"
languageCode: "zh-CN"
title: "耻辱墙"
theme: "anubis"

menu:
  main:
  - identifier: about
    name: 关于耻辱墙
    title: 关于耻辱墙
    url: https://github.com/wallofshame/wallofshame.github.io
    weight: 0
  - identifier: tags
    name: 标签
    title: 标签
    url: /tags/
    weight: 1
  - identifier: archive
    name: 归档
    title: 归档
    url: /posts/
    weight: 2

params:
  paginationSinglePost: true
  readMore: false
    
markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
