baseURL: "https://wallofshame.github.io"
languageCode: "zh-CN"
title: "耻辱墙"
theme: "anubis"

menu:
  main:
  - identifier: about
    name: 参与协作
    title: 参与协作
    url: /participate
    weight: 0
  - identifier: tags
    name: 标签
    title: 标签
    url: /tags/
    weight: 1
  - identifier: archive
    name: 归档
    title: 归档
    url: /posts/
    weight: 2

params:
  paginationSinglePost: true
  readMore: false
    
markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
