baseURL: "https://wallofshame.github.io"
languageCode: "zh-CN"
title: "Shame"
theme: "anubis"

menu:
  main:
  - identifier: about
    name: About
    title: About
    url: /about
    weight: 0
  - identifier: tags
    name: Tags
    title: Tags
    url: /tags/
    weight: 1
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 2

params:
  paginationSinglePost: true
  readMore: false
    
markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
